spring.application.name=chat
server.servlet.context-path=/chat
server.port=8081

#logging.level.org.springframework.security=DEBUG

# Set log levels
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

# Enable file logging
logging.file.name=logs/app.log

# Customize log format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n